<?php
/**
 * EstabelecimentoApiTest
 * PHP version 5
 *
 * @category Class
 * @package  br.com.conductor.pier.api.v2.invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace br.com.conductor.pier.api.v2;

use \br.com.conductor.pier.api.v2.invoker\Configuration;
use \br.com.conductor.pier.api.v2.invoker\ApiClient;
use \br.com.conductor.pier.api.v2.invoker\ApiException;
use \br.com.conductor.pier.api.v2.invoker\ObjectSerializer;

/**
 * EstabelecimentoApiTest Class Doc Comment
 *
 * @category Class
 * @package  br.com.conductor.pier.api.v2.invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EstabelecimentoApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for alterarOrigemComercialUsingPUT
     *
     * Alterar Origem Comercial
     *
     */
    public function test_alterarOrigemComercialUsingPUT() {

    }
    
    /**
     * Test case for alterarUsingPUT10
     *
     * Altera uma Maquineta
     *
     */
    public function test_alterarUsingPUT10() {

    }
    
    /**
     * Test case for alterarUsingPUT11
     *
     * Altera uma Regra Opera\u00C3\u00A7\u00C3\u00A3o
     *
     */
    public function test_alterarUsingPUT11() {

    }
    
    /**
     * Test case for alterarUsingPUT15
     *
     * Altera um Telefone do estabelecimento
     *
     */
    public function test_alterarUsingPUT15() {

    }
    
    /**
     * Test case for alterarUsingPUT17
     *
     * Altera um Terminal
     *
     */
    public function test_alterarUsingPUT17() {

    }
    
    /**
     * Test case for alterarUsingPUT6
     *
     * Alterar um estabelecimento
     *
     */
    public function test_alterarUsingPUT6() {

    }
    
    /**
     * Test case for alterarUsingPUT8
     *
     * Alterar Grupo Econ\u00C3\u00B4mico
     *
     */
    public function test_alterarUsingPUT8() {

    }
    
    /**
     * Test case for cadastrarOrigemComercialUsingPOST
     *
     * Cadastrar Origem Comercial
     *
     */
    public function test_cadastrarOrigemComercialUsingPOST() {

    }
    
    /**
     * Test case for cadastrarUsingPOST2
     *
     * Cadastrar um estabelecimento
     *
     */
    public function test_cadastrarUsingPOST2() {

    }
    
    /**
     * Test case for cadastrarUsingPOST3
     *
     * Cadastrar Grupo Econ\u00C3\u00B4mico
     *
     */
    public function test_cadastrarUsingPOST3() {

    }
    
    /**
     * Test case for consultaOperacaoUsingGET
     *
     * Apresenta dados de um determinado tipo de opera\u00C3\u00A7\u00C3\u00A3o
     *
     */
    public function test_consultaOperacaoUsingGET() {

    }
    
    /**
     * Test case for consultarOrigemComercialUsingGET
     *
     * Consultar Origem Comercial
     *
     */
    public function test_consultarOrigemComercialUsingGET() {

    }
    
    /**
     * Test case for consultarUsingGET16
     *
     * Consultar estabelecimento por id
     *
     */
    public function test_consultarUsingGET16() {

    }
    
    /**
     * Test case for consultarUsingGET18
     *
     * Consultar grupo econ\u00C3\u00B4mico
     *
     */
    public function test_consultarUsingGET18() {

    }
    
    /**
     * Test case for consultarUsingGET20
     *
     * Apresenta os dados de uma determinada maquineta
     *
     */
    public function test_consultarUsingGET20() {

    }
    
    /**
     * Test case for consultarUsingGET21
     *
     * Apresenta os dados de uma determinada Regra Opera\u00C3\u00A7\u00C3\u00A3o
     *
     */
    public function test_consultarUsingGET21() {

    }
    
    /**
     * Test case for consultarUsingGET29
     *
     * Apresenta os dados de um determinado telefone de um estabelecimento
     *
     */
    public function test_consultarUsingGET29() {

    }
    
    /**
     * Test case for consultarUsingGET31
     *
     * Apresenta os dados de um determinado Terminal
     *
     */
    public function test_consultarUsingGET31() {

    }
    
    /**
     * Test case for consultarUsingGET43
     *
     * Apresenta os dados de um determinado V\u00C3\u00ADnculo
     *
     */
    public function test_consultarUsingGET43() {

    }
    
    /**
     * Test case for desabilitarVinculoUsingPOST
     *
     * Desabilitar um V\u00C3\u00ADnculo
     *
     */
    public function test_desabilitarVinculoUsingPOST() {

    }
    
    /**
     * Test case for desabilitarVinculoUsingPOST1
     *
     * Desabilitar um v\u00C3\u00ADnculo opera\u00C3\u00A7\u00C3\u00A3o
     *
     */
    public function test_desabilitarVinculoUsingPOST1() {

    }
    
    /**
     * Test case for habilitarVinculoUsingPOST
     *
     * Habilitar um V\u00C3\u00ADnculo
     *
     */
    public function test_habilitarVinculoUsingPOST() {

    }
    
    /**
     * Test case for habilitarVinculoUsingPOST1
     *
     * Habilitar um v\u00C3\u00ADnculo opera\u00C3\u00A7\u00C3\u00A3o
     *
     */
    public function test_habilitarVinculoUsingPOST1() {

    }
    
    /**
     * Test case for listaOperacaoUsingGET
     *
     * Apresenta dados de opera\u00C3\u00A7\u00C3\u00B5es em uma lista
     *
     */
    public function test_listaOperacaoUsingGET() {

    }
    
    /**
     * Test case for listarMCCUsingGET
     *
     * Lista os MCCs
     *
     */
    public function test_listarMCCUsingGET() {

    }
    
    /**
     * Test case for listarOrigensComerciaisUsingGET
     *
     * Listar Origens Comerciais
     *
     */
    public function test_listarOrigensComerciaisUsingGET() {

    }
    
    /**
     * Test case for listarTiposAdquirentesUsingGET
     *
     * Lista os Tipos de adquirentes
     *
     */
    public function test_listarTiposAdquirentesUsingGET() {

    }
    
    /**
     * Test case for listarTiposMaquinetasUsingGET
     *
     * Lista os Tipos de  Maquinetas
     *
     */
    public function test_listarTiposMaquinetasUsingGET() {

    }
    
    /**
     * Test case for listarTiposTerminaisUsingGET1
     *
     * Lista os Tipos Terminais
     *
     */
    public function test_listarTiposTerminaisUsingGET1() {

    }
    
    /**
     * Test case for listarUsingGET21
     *
     * Lista Estabelecimentos
     *
     */
    public function test_listarUsingGET21() {

    }
    
    /**
     * Test case for listarUsingGET23
     *
     * Listar grupos econ\u00C3\u00B4micos
     *
     */
    public function test_listarUsingGET23() {

    }
    
    /**
     * Test case for listarUsingGET25
     *
     * Lista as Maquinetas
     *
     */
    public function test_listarUsingGET25() {

    }
    
    /**
     * Test case for listarUsingGET26
     *
     * Lista os tipos de moedas do emissor 
     *
     */
    public function test_listarUsingGET26() {

    }
    
    /**
     * Test case for listarUsingGET27
     *
     * Lista as Regras Opera\u00C3\u00A7\u00C3\u00B5es
     *
     */
    public function test_listarUsingGET27() {

    }
    
    /**
     * Test case for listarUsingGET38
     *
     * Lista os Telefones Estabelecimentos
     *
     */
    public function test_listarUsingGET38() {

    }
    
    /**
     * Test case for listarUsingGET40
     *
     * Lista os Terminais cadastrados no Emissor
     *
     */
    public function test_listarUsingGET40() {

    }
    
    /**
     * Test case for listarUsingGET51
     *
     * Lista os V\u00C3\u00ADnculos dos estabelecimento com os adquirentes
     *
     */
    public function test_listarUsingGET51() {

    }
    
    /**
     * Test case for listarUsingGET52
     *
     * Lista os v\u00C3\u00ADnculos cadastrados no Emissor
     *
     */
    public function test_listarUsingGET52() {

    }
    
    /**
     * Test case for salvarUsingPOST16
     *
     * Realiza o cadastro de uma nova maquineta para um estabelecimento 
     *
     */
    public function test_salvarUsingPOST16() {

    }
    
    /**
     * Test case for salvarUsingPOST17
     *
     * Realiza o cadastro de uma nova Regra Opera\u00C3\u00A7\u00C3\u00A3o
     *
     */
    public function test_salvarUsingPOST17() {

    }
    
    /**
     * Test case for salvarUsingPOST22
     *
     * Realiza o cadastro de um novo telefone para um estabelecimento 
     *
     */
    public function test_salvarUsingPOST22() {

    }
    
    /**
     * Test case for salvarUsingPOST24
     *
     * Realiza o cadastro de um novo Terminal
     *
     */
    public function test_salvarUsingPOST24() {

    }
    
    /**
     * Test case for salvarUsingPOST29
     *
     * Realiza o cadastro de um novo VinculoEstabelecimentoAdquirente
     *
     */
    public function test_salvarUsingPOST29() {

    }
    
}
