<?php
/**
 * GlobaltagboletoApiTest
 * PHP version 5
 *
 * @category Class
 * @package  br.com.conductor.pier.api.v2.invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Please update the test case below to test the endpoint.
 */

namespace br.com.conductor.pier.api.v2;

use \br.com.conductor.pier.api.v2.invoker\Configuration;
use \br.com.conductor.pier.api.v2.invoker\ApiClient;
use \br.com.conductor.pier.api.v2.invoker\ApiException;
use \br.com.conductor.pier.api.v2.invoker\ObjectSerializer;

/**
 * GlobaltagboletoApiTest Class Doc Comment
 *
 * @category Class
 * @package  br.com.conductor.pier.api.v2.invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class GlobaltagboletoApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running each test case
     */
    public static function setUpBeforeClass() {

    }

    /**
     * Clean up after running each test case
     */
    public static function tearDownAfterClass() {

    }

    
    /**
     * Test case for consultarUsingGET34
     *
     * {{{boleto_resource_consultar}}}
     *
     */
    public function test_consultarUsingGET34() {

    }
    
    /**
     * Test case for enviarBoletoEmailUsingPOST
     *
     * {{{boleto_resource_enviar_boleto_email}}}
     *
     */
    public function test_enviarBoletoEmailUsingPOST() {

    }
    
    /**
     * Test case for gerarBoletoUsingPOST
     *
     * {{{boleto_resource_gerar_boleto}}}
     *
     */
    public function test_gerarBoletoUsingPOST() {

    }
    
    /**
     * Test case for listarUsingGET45
     *
     * {{{boleto_resource_listar}}}
     *
     */
    public function test_listarUsingGET45() {

    }
    
    /**
     * Test case for registrarBoletoUsingPOST
     *
     * {{{registro_cobranca_resource_registrar_boleto}}}
     *
     */
    public function test_registrarBoletoUsingPOST() {

    }
    
    /**
     * Test case for visualizarBoletoUsingGET
     *
     * {{{boleto_resource_visualizar_boleto}}}
     *
     */
    public function test_visualizarBoletoUsingGET() {

    }
    
}
