<?php
/**
 * ConsultarContaResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  br.com.conductor.pier.api.v1.invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace br.com.conductor.pier.api.v1.model;

use \ArrayAccess;
/**
 * ConsultarContaResponse Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     br.com.conductor.pier.api.v1.invoker
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConsultarContaResponse implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'cod_retorno' => 'int',
        'codigo_retorno' => 'int',
        'contas' => '\br.com.conductor.pier.api.v1.model\ContaCartaoResponse[]',
        'descricao_retorno' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'cod_retorno' => 'codRetorno',
        'codigo_retorno' => 'codigoRetorno',
        'contas' => 'contas',
        'descricao_retorno' => 'descricaoRetorno'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'cod_retorno' => 'setCodRetorno',
        'codigo_retorno' => 'setCodigoRetorno',
        'contas' => 'setContas',
        'descricao_retorno' => 'setDescricaoRetorno'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'cod_retorno' => 'getCodRetorno',
        'codigo_retorno' => 'getCodigoRetorno',
        'contas' => 'getContas',
        'descricao_retorno' => 'getDescricaoRetorno'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $cod_retorno 
      * @var int
      */
    protected $cod_retorno;
    
    /**
      * $codigo_retorno 
      * @var int
      */
    protected $codigo_retorno;
    
    /**
      * $contas 
      * @var \br.com.conductor.pier.api.v1.model\ContaCartaoResponse[]
      */
    protected $contas;
    
    /**
      * $descricao_retorno 
      * @var string
      */
    protected $descricao_retorno;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->cod_retorno = $data["cod_retorno"];
            $this->codigo_retorno = $data["codigo_retorno"];
            $this->contas = $data["contas"];
            $this->descricao_retorno = $data["descricao_retorno"];
        }
    }
    
    /**
     * Gets cod_retorno
     * @return int
     */
    public function getCodRetorno()
    {
        return $this->cod_retorno;
    }
  
    /**
     * Sets cod_retorno
     * @param int $cod_retorno 
     * @return $this
     */
    public function setCodRetorno($cod_retorno)
    {
        
        $this->cod_retorno = $cod_retorno;
        return $this;
    }
    
    /**
     * Gets codigo_retorno
     * @return int
     */
    public function getCodigoRetorno()
    {
        return $this->codigo_retorno;
    }
  
    /**
     * Sets codigo_retorno
     * @param int $codigo_retorno 
     * @return $this
     */
    public function setCodigoRetorno($codigo_retorno)
    {
        
        $this->codigo_retorno = $codigo_retorno;
        return $this;
    }
    
    /**
     * Gets contas
     * @return \br.com.conductor.pier.api.v1.model\ContaCartaoResponse[]
     */
    public function getContas()
    {
        return $this->contas;
    }
  
    /**
     * Sets contas
     * @param \br.com.conductor.pier.api.v1.model\ContaCartaoResponse[] $contas 
     * @return $this
     */
    public function setContas($contas)
    {
        
        $this->contas = $contas;
        return $this;
    }
    
    /**
     * Gets descricao_retorno
     * @return string
     */
    public function getDescricaoRetorno()
    {
        return $this->descricao_retorno;
    }
  
    /**
     * Sets descricao_retorno
     * @param string $descricao_retorno 
     * @return $this
     */
    public function setDescricaoRetorno($descricao_retorno)
    {
        
        $this->descricao_retorno = $descricao_retorno;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\br.com.conductor.pier.api.v1.invoker\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\br.com.conductor.pier.api.v1.invoker\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
