<?php
/**
 * CartaoResponseOld
 *
 * PHP version 5
 *
 * @category Class
 * @package  br.com.conductor.pier.api.v1_1.invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace br.com.conductor.pier.api.v1_1.model;

use \ArrayAccess;
/**
 * CartaoResponseOld Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     br.com.conductor.pier.api.v1_1.invoker
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CartaoResponseOld implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'bin' => 'int',
        'cod_retorno' => 'int',
        'codigo_desbloqueio' => 'string',
        'criptografia_hsm' => 'string',
        'data_emissao' => '\DateTime',
        'data_validade' => '\DateTime',
        'data_vencimento_padrao' => 'string',
        'descricao_retorno' => 'string',
        'estagio_cartao' => 'int',
        'estagio_data' => '\DateTime',
        'flag_reversao' => 'bool',
        'flag_senha' => 'bool',
        'id_cartao' => 'int',
        'id_conta' => 'int',
        'id_emissor' => 'int',
        'id_log' => 'string',
        'id_pessoa_fisica' => 'int',
        'id_produto' => 'int',
        'nome_plastico' => 'string',
        'numero_cartao' => 'string',
        'numero_cartao_real' => 'string',
        'status_cartao' => 'int',
        'status_data' => '\DateTime'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'bin' => 'bin',
        'cod_retorno' => 'codRetorno',
        'codigo_desbloqueio' => 'codigoDesbloqueio',
        'criptografia_hsm' => 'criptografiaHSM',
        'data_emissao' => 'dataEmissao',
        'data_validade' => 'dataValidade',
        'data_vencimento_padrao' => 'dataVencimentoPadrao',
        'descricao_retorno' => 'descricaoRetorno',
        'estagio_cartao' => 'estagioCartao',
        'estagio_data' => 'estagioData',
        'flag_reversao' => 'flagReversao',
        'flag_senha' => 'flagSenha',
        'id_cartao' => 'idCartao',
        'id_conta' => 'idConta',
        'id_emissor' => 'idEmissor',
        'id_log' => 'idLog',
        'id_pessoa_fisica' => 'idPessoaFisica',
        'id_produto' => 'idProduto',
        'nome_plastico' => 'nomePlastico',
        'numero_cartao' => 'numeroCartao',
        'numero_cartao_real' => 'numeroCartaoReal',
        'status_cartao' => 'statusCartao',
        'status_data' => 'statusData'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'bin' => 'setBin',
        'cod_retorno' => 'setCodRetorno',
        'codigo_desbloqueio' => 'setCodigoDesbloqueio',
        'criptografia_hsm' => 'setCriptografiaHsm',
        'data_emissao' => 'setDataEmissao',
        'data_validade' => 'setDataValidade',
        'data_vencimento_padrao' => 'setDataVencimentoPadrao',
        'descricao_retorno' => 'setDescricaoRetorno',
        'estagio_cartao' => 'setEstagioCartao',
        'estagio_data' => 'setEstagioData',
        'flag_reversao' => 'setFlagReversao',
        'flag_senha' => 'setFlagSenha',
        'id_cartao' => 'setIdCartao',
        'id_conta' => 'setIdConta',
        'id_emissor' => 'setIdEmissor',
        'id_log' => 'setIdLog',
        'id_pessoa_fisica' => 'setIdPessoaFisica',
        'id_produto' => 'setIdProduto',
        'nome_plastico' => 'setNomePlastico',
        'numero_cartao' => 'setNumeroCartao',
        'numero_cartao_real' => 'setNumeroCartaoReal',
        'status_cartao' => 'setStatusCartao',
        'status_data' => 'setStatusData'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'bin' => 'getBin',
        'cod_retorno' => 'getCodRetorno',
        'codigo_desbloqueio' => 'getCodigoDesbloqueio',
        'criptografia_hsm' => 'getCriptografiaHsm',
        'data_emissao' => 'getDataEmissao',
        'data_validade' => 'getDataValidade',
        'data_vencimento_padrao' => 'getDataVencimentoPadrao',
        'descricao_retorno' => 'getDescricaoRetorno',
        'estagio_cartao' => 'getEstagioCartao',
        'estagio_data' => 'getEstagioData',
        'flag_reversao' => 'getFlagReversao',
        'flag_senha' => 'getFlagSenha',
        'id_cartao' => 'getIdCartao',
        'id_conta' => 'getIdConta',
        'id_emissor' => 'getIdEmissor',
        'id_log' => 'getIdLog',
        'id_pessoa_fisica' => 'getIdPessoaFisica',
        'id_produto' => 'getIdProduto',
        'nome_plastico' => 'getNomePlastico',
        'numero_cartao' => 'getNumeroCartao',
        'numero_cartao_real' => 'getNumeroCartaoReal',
        'status_cartao' => 'getStatusCartao',
        'status_data' => 'getStatusData'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $bin 
      * @var int
      */
    protected $bin;
    
    /**
      * $cod_retorno 
      * @var int
      */
    protected $cod_retorno;
    
    /**
      * $codigo_desbloqueio 
      * @var string
      */
    protected $codigo_desbloqueio;
    
    /**
      * $criptografia_hsm 
      * @var string
      */
    protected $criptografia_hsm;
    
    /**
      * $data_emissao 
      * @var \DateTime
      */
    protected $data_emissao;
    
    /**
      * $data_validade 
      * @var \DateTime
      */
    protected $data_validade;
    
    /**
      * $data_vencimento_padrao 
      * @var string
      */
    protected $data_vencimento_padrao;
    
    /**
      * $descricao_retorno 
      * @var string
      */
    protected $descricao_retorno;
    
    /**
      * $estagio_cartao 
      * @var int
      */
    protected $estagio_cartao;
    
    /**
      * $estagio_data 
      * @var \DateTime
      */
    protected $estagio_data;
    
    /**
      * $flag_reversao 
      * @var bool
      */
    protected $flag_reversao;
    
    /**
      * $flag_senha 
      * @var bool
      */
    protected $flag_senha;
    
    /**
      * $id_cartao 
      * @var int
      */
    protected $id_cartao;
    
    /**
      * $id_conta 
      * @var int
      */
    protected $id_conta;
    
    /**
      * $id_emissor 
      * @var int
      */
    protected $id_emissor;
    
    /**
      * $id_log 
      * @var string
      */
    protected $id_log;
    
    /**
      * $id_pessoa_fisica 
      * @var int
      */
    protected $id_pessoa_fisica;
    
    /**
      * $id_produto 
      * @var int
      */
    protected $id_produto;
    
    /**
      * $nome_plastico 
      * @var string
      */
    protected $nome_plastico;
    
    /**
      * $numero_cartao 
      * @var string
      */
    protected $numero_cartao;
    
    /**
      * $numero_cartao_real 
      * @var string
      */
    protected $numero_cartao_real;
    
    /**
      * $status_cartao 
      * @var int
      */
    protected $status_cartao;
    
    /**
      * $status_data 
      * @var \DateTime
      */
    protected $status_data;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->bin = $data["bin"];
            $this->cod_retorno = $data["cod_retorno"];
            $this->codigo_desbloqueio = $data["codigo_desbloqueio"];
            $this->criptografia_hsm = $data["criptografia_hsm"];
            $this->data_emissao = $data["data_emissao"];
            $this->data_validade = $data["data_validade"];
            $this->data_vencimento_padrao = $data["data_vencimento_padrao"];
            $this->descricao_retorno = $data["descricao_retorno"];
            $this->estagio_cartao = $data["estagio_cartao"];
            $this->estagio_data = $data["estagio_data"];
            $this->flag_reversao = $data["flag_reversao"];
            $this->flag_senha = $data["flag_senha"];
            $this->id_cartao = $data["id_cartao"];
            $this->id_conta = $data["id_conta"];
            $this->id_emissor = $data["id_emissor"];
            $this->id_log = $data["id_log"];
            $this->id_pessoa_fisica = $data["id_pessoa_fisica"];
            $this->id_produto = $data["id_produto"];
            $this->nome_plastico = $data["nome_plastico"];
            $this->numero_cartao = $data["numero_cartao"];
            $this->numero_cartao_real = $data["numero_cartao_real"];
            $this->status_cartao = $data["status_cartao"];
            $this->status_data = $data["status_data"];
        }
    }
    
    /**
     * Gets bin
     * @return int
     */
    public function getBin()
    {
        return $this->bin;
    }
  
    /**
     * Sets bin
     * @param int $bin 
     * @return $this
     */
    public function setBin($bin)
    {
        
        $this->bin = $bin;
        return $this;
    }
    
    /**
     * Gets cod_retorno
     * @return int
     */
    public function getCodRetorno()
    {
        return $this->cod_retorno;
    }
  
    /**
     * Sets cod_retorno
     * @param int $cod_retorno 
     * @return $this
     */
    public function setCodRetorno($cod_retorno)
    {
        
        $this->cod_retorno = $cod_retorno;
        return $this;
    }
    
    /**
     * Gets codigo_desbloqueio
     * @return string
     */
    public function getCodigoDesbloqueio()
    {
        return $this->codigo_desbloqueio;
    }
  
    /**
     * Sets codigo_desbloqueio
     * @param string $codigo_desbloqueio 
     * @return $this
     */
    public function setCodigoDesbloqueio($codigo_desbloqueio)
    {
        
        $this->codigo_desbloqueio = $codigo_desbloqueio;
        return $this;
    }
    
    /**
     * Gets criptografia_hsm
     * @return string
     */
    public function getCriptografiaHsm()
    {
        return $this->criptografia_hsm;
    }
  
    /**
     * Sets criptografia_hsm
     * @param string $criptografia_hsm 
     * @return $this
     */
    public function setCriptografiaHsm($criptografia_hsm)
    {
        
        $this->criptografia_hsm = $criptografia_hsm;
        return $this;
    }
    
    /**
     * Gets data_emissao
     * @return \DateTime
     */
    public function getDataEmissao()
    {
        return $this->data_emissao;
    }
  
    /**
     * Sets data_emissao
     * @param \DateTime $data_emissao 
     * @return $this
     */
    public function setDataEmissao($data_emissao)
    {
        
        $this->data_emissao = $data_emissao;
        return $this;
    }
    
    /**
     * Gets data_validade
     * @return \DateTime
     */
    public function getDataValidade()
    {
        return $this->data_validade;
    }
  
    /**
     * Sets data_validade
     * @param \DateTime $data_validade 
     * @return $this
     */
    public function setDataValidade($data_validade)
    {
        
        $this->data_validade = $data_validade;
        return $this;
    }
    
    /**
     * Gets data_vencimento_padrao
     * @return string
     */
    public function getDataVencimentoPadrao()
    {
        return $this->data_vencimento_padrao;
    }
  
    /**
     * Sets data_vencimento_padrao
     * @param string $data_vencimento_padrao 
     * @return $this
     */
    public function setDataVencimentoPadrao($data_vencimento_padrao)
    {
        
        $this->data_vencimento_padrao = $data_vencimento_padrao;
        return $this;
    }
    
    /**
     * Gets descricao_retorno
     * @return string
     */
    public function getDescricaoRetorno()
    {
        return $this->descricao_retorno;
    }
  
    /**
     * Sets descricao_retorno
     * @param string $descricao_retorno 
     * @return $this
     */
    public function setDescricaoRetorno($descricao_retorno)
    {
        
        $this->descricao_retorno = $descricao_retorno;
        return $this;
    }
    
    /**
     * Gets estagio_cartao
     * @return int
     */
    public function getEstagioCartao()
    {
        return $this->estagio_cartao;
    }
  
    /**
     * Sets estagio_cartao
     * @param int $estagio_cartao 
     * @return $this
     */
    public function setEstagioCartao($estagio_cartao)
    {
        
        $this->estagio_cartao = $estagio_cartao;
        return $this;
    }
    
    /**
     * Gets estagio_data
     * @return \DateTime
     */
    public function getEstagioData()
    {
        return $this->estagio_data;
    }
  
    /**
     * Sets estagio_data
     * @param \DateTime $estagio_data 
     * @return $this
     */
    public function setEstagioData($estagio_data)
    {
        
        $this->estagio_data = $estagio_data;
        return $this;
    }
    
    /**
     * Gets flag_reversao
     * @return bool
     */
    public function getFlagReversao()
    {
        return $this->flag_reversao;
    }
  
    /**
     * Sets flag_reversao
     * @param bool $flag_reversao 
     * @return $this
     */
    public function setFlagReversao($flag_reversao)
    {
        
        $this->flag_reversao = $flag_reversao;
        return $this;
    }
    
    /**
     * Gets flag_senha
     * @return bool
     */
    public function getFlagSenha()
    {
        return $this->flag_senha;
    }
  
    /**
     * Sets flag_senha
     * @param bool $flag_senha 
     * @return $this
     */
    public function setFlagSenha($flag_senha)
    {
        
        $this->flag_senha = $flag_senha;
        return $this;
    }
    
    /**
     * Gets id_cartao
     * @return int
     */
    public function getIdCartao()
    {
        return $this->id_cartao;
    }
  
    /**
     * Sets id_cartao
     * @param int $id_cartao 
     * @return $this
     */
    public function setIdCartao($id_cartao)
    {
        
        $this->id_cartao = $id_cartao;
        return $this;
    }
    
    /**
     * Gets id_conta
     * @return int
     */
    public function getIdConta()
    {
        return $this->id_conta;
    }
  
    /**
     * Sets id_conta
     * @param int $id_conta 
     * @return $this
     */
    public function setIdConta($id_conta)
    {
        
        $this->id_conta = $id_conta;
        return $this;
    }
    
    /**
     * Gets id_emissor
     * @return int
     */
    public function getIdEmissor()
    {
        return $this->id_emissor;
    }
  
    /**
     * Sets id_emissor
     * @param int $id_emissor 
     * @return $this
     */
    public function setIdEmissor($id_emissor)
    {
        
        $this->id_emissor = $id_emissor;
        return $this;
    }
    
    /**
     * Gets id_log
     * @return string
     */
    public function getIdLog()
    {
        return $this->id_log;
    }
  
    /**
     * Sets id_log
     * @param string $id_log 
     * @return $this
     */
    public function setIdLog($id_log)
    {
        
        $this->id_log = $id_log;
        return $this;
    }
    
    /**
     * Gets id_pessoa_fisica
     * @return int
     */
    public function getIdPessoaFisica()
    {
        return $this->id_pessoa_fisica;
    }
  
    /**
     * Sets id_pessoa_fisica
     * @param int $id_pessoa_fisica 
     * @return $this
     */
    public function setIdPessoaFisica($id_pessoa_fisica)
    {
        
        $this->id_pessoa_fisica = $id_pessoa_fisica;
        return $this;
    }
    
    /**
     * Gets id_produto
     * @return int
     */
    public function getIdProduto()
    {
        return $this->id_produto;
    }
  
    /**
     * Sets id_produto
     * @param int $id_produto 
     * @return $this
     */
    public function setIdProduto($id_produto)
    {
        
        $this->id_produto = $id_produto;
        return $this;
    }
    
    /**
     * Gets nome_plastico
     * @return string
     */
    public function getNomePlastico()
    {
        return $this->nome_plastico;
    }
  
    /**
     * Sets nome_plastico
     * @param string $nome_plastico 
     * @return $this
     */
    public function setNomePlastico($nome_plastico)
    {
        
        $this->nome_plastico = $nome_plastico;
        return $this;
    }
    
    /**
     * Gets numero_cartao
     * @return string
     */
    public function getNumeroCartao()
    {
        return $this->numero_cartao;
    }
  
    /**
     * Sets numero_cartao
     * @param string $numero_cartao 
     * @return $this
     */
    public function setNumeroCartao($numero_cartao)
    {
        
        $this->numero_cartao = $numero_cartao;
        return $this;
    }
    
    /**
     * Gets numero_cartao_real
     * @return string
     */
    public function getNumeroCartaoReal()
    {
        return $this->numero_cartao_real;
    }
  
    /**
     * Sets numero_cartao_real
     * @param string $numero_cartao_real 
     * @return $this
     */
    public function setNumeroCartaoReal($numero_cartao_real)
    {
        
        $this->numero_cartao_real = $numero_cartao_real;
        return $this;
    }
    
    /**
     * Gets status_cartao
     * @return int
     */
    public function getStatusCartao()
    {
        return $this->status_cartao;
    }
  
    /**
     * Sets status_cartao
     * @param int $status_cartao 
     * @return $this
     */
    public function setStatusCartao($status_cartao)
    {
        
        $this->status_cartao = $status_cartao;
        return $this;
    }
    
    /**
     * Gets status_data
     * @return \DateTime
     */
    public function getStatusData()
    {
        return $this->status_data;
    }
  
    /**
     * Sets status_data
     * @param \DateTime $status_data 
     * @return $this
     */
    public function setStatusData($status_data)
    {
        
        $this->status_data = $status_data;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\br.com.conductor.pier.api.v1_1.invoker\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\br.com.conductor.pier.api.v1_1.invoker\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
