<?php
/**
 * DadosPortadorRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  br.com.conductor.pier.api.v2.invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace br.com.conductor.pier.api.v2.model;

use \ArrayAccess;
/**
 * DadosPortadorRequest Class Doc Comment
 *
 * @category    Class
 * @description Par\u00E2metros de requisi\u00E7\u00E3o para valida\u00E7\u00E3o dos dados do portador.
 * @package     br.com.conductor.pier.api.v2.invoker
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DadosPortadorRequest implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'cartao' => 'string',
        'cpf' => 'string',
        'nome' => 'string',
        'data_nascimento' => 'string',
        'cep_residencial' => 'string',
        'email' => 'string',
        'ddd' => 'string',
        'telefone' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'cartao' => 'cartao',
        'cpf' => 'cpf',
        'nome' => 'nome',
        'data_nascimento' => 'dataNascimento',
        'cep_residencial' => 'cepResidencial',
        'email' => 'email',
        'ddd' => 'ddd',
        'telefone' => 'telefone'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'cartao' => 'setCartao',
        'cpf' => 'setCpf',
        'nome' => 'setNome',
        'data_nascimento' => 'setDataNascimento',
        'cep_residencial' => 'setCepResidencial',
        'email' => 'setEmail',
        'ddd' => 'setDdd',
        'telefone' => 'setTelefone'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'cartao' => 'getCartao',
        'cpf' => 'getCpf',
        'nome' => 'getNome',
        'data_nascimento' => 'getDataNascimento',
        'cep_residencial' => 'getCepResidencial',
        'email' => 'getEmail',
        'ddd' => 'getDdd',
        'telefone' => 'getTelefone'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $cartao N\u00FAmero do cart\u00E3o.
      * @var string
      */
    protected $cartao;
    
    /**
      * $cpf N\u00FAmero do CPF.
      * @var string
      */
    protected $cpf;
    
    /**
      * $nome Nome do portador.
      * @var string
      */
    protected $nome;
    
    /**
      * $data_nascimento Data de nascimento do portador do cart\u00E3o.
      * @var string
      */
    protected $data_nascimento;
    
    /**
      * $cep_residencial CEP da resid\u00EAncia do portador da conta.
      * @var string
      */
    protected $cep_residencial;
    
    /**
      * $email E-mail do portador do cart\u00E3o.
      * @var string
      */
    protected $email;
    
    /**
      * $ddd DDD do n\u00FAmero de telefone do portador do cart\u00E3o.
      * @var string
      */
    protected $ddd;
    
    /**
      * $telefone N\u00FAmero do telefone do portador do cart\u00E3o.
      * @var string
      */
    protected $telefone;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->cartao = $data["cartao"];
            $this->cpf = $data["cpf"];
            $this->nome = $data["nome"];
            $this->data_nascimento = $data["data_nascimento"];
            $this->cep_residencial = $data["cep_residencial"];
            $this->email = $data["email"];
            $this->ddd = $data["ddd"];
            $this->telefone = $data["telefone"];
        }
    }
    
    /**
     * Gets cartao
     * @return string
     */
    public function getCartao()
    {
        return $this->cartao;
    }
  
    /**
     * Sets cartao
     * @param string $cartao N\u00FAmero do cart\u00E3o.
     * @return $this
     */
    public function setCartao($cartao)
    {
        
        $this->cartao = $cartao;
        return $this;
    }
    
    /**
     * Gets cpf
     * @return string
     */
    public function getCpf()
    {
        return $this->cpf;
    }
  
    /**
     * Sets cpf
     * @param string $cpf N\u00FAmero do CPF.
     * @return $this
     */
    public function setCpf($cpf)
    {
        
        $this->cpf = $cpf;
        return $this;
    }
    
    /**
     * Gets nome
     * @return string
     */
    public function getNome()
    {
        return $this->nome;
    }
  
    /**
     * Sets nome
     * @param string $nome Nome do portador.
     * @return $this
     */
    public function setNome($nome)
    {
        
        $this->nome = $nome;
        return $this;
    }
    
    /**
     * Gets data_nascimento
     * @return string
     */
    public function getDataNascimento()
    {
        return $this->data_nascimento;
    }
  
    /**
     * Sets data_nascimento
     * @param string $data_nascimento Data de nascimento do portador do cart\u00E3o.
     * @return $this
     */
    public function setDataNascimento($data_nascimento)
    {
        
        $this->data_nascimento = $data_nascimento;
        return $this;
    }
    
    /**
     * Gets cep_residencial
     * @return string
     */
    public function getCepResidencial()
    {
        return $this->cep_residencial;
    }
  
    /**
     * Sets cep_residencial
     * @param string $cep_residencial CEP da resid\u00EAncia do portador da conta.
     * @return $this
     */
    public function setCepResidencial($cep_residencial)
    {
        
        $this->cep_residencial = $cep_residencial;
        return $this;
    }
    
    /**
     * Gets email
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }
  
    /**
     * Sets email
     * @param string $email E-mail do portador do cart\u00E3o.
     * @return $this
     */
    public function setEmail($email)
    {
        
        $this->email = $email;
        return $this;
    }
    
    /**
     * Gets ddd
     * @return string
     */
    public function getDdd()
    {
        return $this->ddd;
    }
  
    /**
     * Sets ddd
     * @param string $ddd DDD do n\u00FAmero de telefone do portador do cart\u00E3o.
     * @return $this
     */
    public function setDdd($ddd)
    {
        
        $this->ddd = $ddd;
        return $this;
    }
    
    /**
     * Gets telefone
     * @return string
     */
    public function getTelefone()
    {
        return $this->telefone;
    }
  
    /**
     * Sets telefone
     * @param string $telefone N\u00FAmero do telefone do portador do cart\u00E3o.
     * @return $this
     */
    public function setTelefone($telefone)
    {
        
        $this->telefone = $telefone;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\br.com.conductor.pier.api.v2.invoker\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\br.com.conductor.pier.api.v2.invoker\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
