<?php
/**
 * ParcelamentoTransferenciaResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  br.com.conductor.pier.api.v2.invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace br.com.conductor.pier.api.v2.model;

use \ArrayAccess;
/**
 * ParcelamentoTransferenciaResponse Class Doc Comment
 *
 * @category    Class
 * @description Detalhe do plano de parcelamento para Transfer\u00C3\u00AAncia de cr\u00C3\u00A9dito para contas banc\u00C3\u00A1rias
 * @package     br.com.conductor.pier.api.v2.invoker
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ParcelamentoTransferenciaResponse implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'numero_parcela' => 'string',
        'valor_primeira_parcela' => 'Number',
        'valor_demais_parcelas' => 'Number',
        'taxa_juros' => 'Number',
        'cet_anual' => 'Number'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'numero_parcela' => 'numeroParcela',
        'valor_primeira_parcela' => 'valorPrimeiraParcela',
        'valor_demais_parcelas' => 'valorDemaisParcelas',
        'taxa_juros' => 'taxaJuros',
        'cet_anual' => 'cetAnual'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'numero_parcela' => 'setNumeroParcela',
        'valor_primeira_parcela' => 'setValorPrimeiraParcela',
        'valor_demais_parcelas' => 'setValorDemaisParcelas',
        'taxa_juros' => 'setTaxaJuros',
        'cet_anual' => 'setCetAnual'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'numero_parcela' => 'getNumeroParcela',
        'valor_primeira_parcela' => 'getValorPrimeiraParcela',
        'valor_demais_parcelas' => 'getValorDemaisParcelas',
        'taxa_juros' => 'getTaxaJuros',
        'cet_anual' => 'getCetAnual'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $numero_parcela N\u00C3\u00BAmero de parcelas dispon\u00C3\u00ADveis.
      * @var string
      */
    protected $numero_parcela;
    
    /**
      * $valor_primeira_parcela Valor da primeira parcela.
      * @var Number
      */
    protected $valor_primeira_parcela;
    
    /**
      * $valor_demais_parcelas Valor das demais parcelas.
      * @var Number
      */
    protected $valor_demais_parcelas;
    
    /**
      * $taxa_juros Valor da taxa de juros.
      * @var Number
      */
    protected $taxa_juros;
    
    /**
      * $cet_anual CET anual.
      * @var Number
      */
    protected $cet_anual;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->numero_parcela = $data["numero_parcela"];
            $this->valor_primeira_parcela = $data["valor_primeira_parcela"];
            $this->valor_demais_parcelas = $data["valor_demais_parcelas"];
            $this->taxa_juros = $data["taxa_juros"];
            $this->cet_anual = $data["cet_anual"];
        }
    }
    
    /**
     * Gets numero_parcela
     * @return string
     */
    public function getNumeroParcela()
    {
        return $this->numero_parcela;
    }
  
    /**
     * Sets numero_parcela
     * @param string $numero_parcela N\u00C3\u00BAmero de parcelas dispon\u00C3\u00ADveis.
     * @return $this
     */
    public function setNumeroParcela($numero_parcela)
    {
        
        $this->numero_parcela = $numero_parcela;
        return $this;
    }
    
    /**
     * Gets valor_primeira_parcela
     * @return Number
     */
    public function getValorPrimeiraParcela()
    {
        return $this->valor_primeira_parcela;
    }
  
    /**
     * Sets valor_primeira_parcela
     * @param Number $valor_primeira_parcela Valor da primeira parcela.
     * @return $this
     */
    public function setValorPrimeiraParcela($valor_primeira_parcela)
    {
        
        $this->valor_primeira_parcela = $valor_primeira_parcela;
        return $this;
    }
    
    /**
     * Gets valor_demais_parcelas
     * @return Number
     */
    public function getValorDemaisParcelas()
    {
        return $this->valor_demais_parcelas;
    }
  
    /**
     * Sets valor_demais_parcelas
     * @param Number $valor_demais_parcelas Valor das demais parcelas.
     * @return $this
     */
    public function setValorDemaisParcelas($valor_demais_parcelas)
    {
        
        $this->valor_demais_parcelas = $valor_demais_parcelas;
        return $this;
    }
    
    /**
     * Gets taxa_juros
     * @return Number
     */
    public function getTaxaJuros()
    {
        return $this->taxa_juros;
    }
  
    /**
     * Sets taxa_juros
     * @param Number $taxa_juros Valor da taxa de juros.
     * @return $this
     */
    public function setTaxaJuros($taxa_juros)
    {
        
        $this->taxa_juros = $taxa_juros;
        return $this;
    }
    
    /**
     * Gets cet_anual
     * @return Number
     */
    public function getCetAnual()
    {
        return $this->cet_anual;
    }
  
    /**
     * Sets cet_anual
     * @param Number $cet_anual CET anual.
     * @return $this
     */
    public function setCetAnual($cet_anual)
    {
        
        $this->cet_anual = $cet_anual;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\br.com.conductor.pier.api.v2.invoker\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\br.com.conductor.pier.api.v2.invoker\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
