<?php
/**
 * PlanoParcelamentoTransferenciaCreditoContaBancariaRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  br.com.conductor.pier.api.v2.invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace br.com.conductor.pier.api.v2.model;

use \ArrayAccess;
/**
 * PlanoParcelamentoTransferenciaCreditoContaBancariaRequest Class Doc Comment
 *
 * @category    Class
 * @description Transfer\u00EAncia cr\u00E9dito conta banc\u00E1ria request
 * @package     br.com.conductor.pier.api.v2.invoker
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PlanoParcelamentoTransferenciaCreditoContaBancariaRequest implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'id_cartao' => 'int',
        'valor_transacao' => 'Number',
        'numero_meses_carencia' => 'int'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'id_cartao' => 'idCartao',
        'valor_transacao' => 'valorTransacao',
        'numero_meses_carencia' => 'numeroMesesCarencia'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'id_cartao' => 'setIdCartao',
        'valor_transacao' => 'setValorTransacao',
        'numero_meses_carencia' => 'setNumeroMesesCarencia'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'id_cartao' => 'getIdCartao',
        'valor_transacao' => 'getValorTransacao',
        'numero_meses_carencia' => 'getNumeroMesesCarencia'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $id_cartao C\u00F3digo de identifica\u00E7\u00E3o do cart\u00E3o.
      * @var int
      */
    protected $id_cartao;
    
    /**
      * $valor_transacao Valor da transa\u00E7\u00E3o com duas casas decimais para os centavos.
      * @var Number
      */
    protected $valor_transacao;
    
    /**
      * $numero_meses_carencia Representa o N\u00FAmero de Meses concedido como car\u00EAncia.
      * @var int
      */
    protected $numero_meses_carencia;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->id_cartao = $data["id_cartao"];
            $this->valor_transacao = $data["valor_transacao"];
            $this->numero_meses_carencia = $data["numero_meses_carencia"];
        }
    }
    
    /**
     * Gets id_cartao
     * @return int
     */
    public function getIdCartao()
    {
        return $this->id_cartao;
    }
  
    /**
     * Sets id_cartao
     * @param int $id_cartao C\u00F3digo de identifica\u00E7\u00E3o do cart\u00E3o.
     * @return $this
     */
    public function setIdCartao($id_cartao)
    {
        
        $this->id_cartao = $id_cartao;
        return $this;
    }
    
    /**
     * Gets valor_transacao
     * @return Number
     */
    public function getValorTransacao()
    {
        return $this->valor_transacao;
    }
  
    /**
     * Sets valor_transacao
     * @param Number $valor_transacao Valor da transa\u00E7\u00E3o com duas casas decimais para os centavos.
     * @return $this
     */
    public function setValorTransacao($valor_transacao)
    {
        
        $this->valor_transacao = $valor_transacao;
        return $this;
    }
    
    /**
     * Gets numero_meses_carencia
     * @return int
     */
    public function getNumeroMesesCarencia()
    {
        return $this->numero_meses_carencia;
    }
  
    /**
     * Sets numero_meses_carencia
     * @param int $numero_meses_carencia Representa o N\u00FAmero de Meses concedido como car\u00EAncia.
     * @return $this
     */
    public function setNumeroMesesCarencia($numero_meses_carencia)
    {
        
        $this->numero_meses_carencia = $numero_meses_carencia;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\br.com.conductor.pier.api.v2.invoker\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\br.com.conductor.pier.api.v2.invoker\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
