<?php
/**
 * RiscoFraudeDetalhadoResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  br.com.conductor.pier.api.v2.invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace br.com.conductor.pier.api.v2.model;

use \ArrayAccess;
/**
 * RiscoFraudeDetalhadoResponse Class Doc Comment
 *
 * @category    Class
 * @description {{{risco_fraude_detalhado_response_description}}}
 * @package     br.com.conductor.pier.api.v2.invoker
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RiscoFraudeDetalhadoResponse implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'id' => 'int',
        'id_tipo_resolucao' => 'int',
        'descricao_tipo_resolucao' => 'string',
        'flag_alto_risco' => 'bool',
        'id_conta' => 'int',
        'id_cartao' => 'int',
        'id_produto' => 'int',
        'id_transacao' => 'int',
        'data_transacao' => 'string',
        'valor_transacao' => 'Number',
        'codigo_moeda_origem' => 'string',
        'valor_origem' => 'Number',
        'codigo_moeda_destino' => 'string',
        'valor_destino' => 'Number',
        'nome_estabelecimento' => 'string',
        'id_pais' => 'string',
        'codigo_resposta_autorizador' => 'string',
        'descricao_resposta_autorizador' => 'string',
        'codigo_resposta_fraude' => 'string',
        'descricao_resposta_fraude' => 'string',
        'origem_transacao' => 'string',
        'codigo_modo_entrada_terminal' => 'string',
        'descricao_modo_entrada_terminal' => 'string',
        'cpf' => 'string',
        'cnpj' => 'string',
        'email' => 'string',
        'telefones' => '\br.com.conductor.pier.api.v2.model\TelefoneResponse[]'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'id' => 'id',
        'id_tipo_resolucao' => 'idTipoResolucao',
        'descricao_tipo_resolucao' => 'descricaoTipoResolucao',
        'flag_alto_risco' => 'flagAltoRisco',
        'id_conta' => 'idConta',
        'id_cartao' => 'idCartao',
        'id_produto' => 'idProduto',
        'id_transacao' => 'idTransacao',
        'data_transacao' => 'dataTransacao',
        'valor_transacao' => 'valorTransacao',
        'codigo_moeda_origem' => 'codigoMoedaOrigem',
        'valor_origem' => 'valorOrigem',
        'codigo_moeda_destino' => 'codigoMoedaDestino',
        'valor_destino' => 'valorDestino',
        'nome_estabelecimento' => 'nomeEstabelecimento',
        'id_pais' => 'idPais',
        'codigo_resposta_autorizador' => 'codigoRespostaAutorizador',
        'descricao_resposta_autorizador' => 'descricaoRespostaAutorizador',
        'codigo_resposta_fraude' => 'codigoRespostaFraude',
        'descricao_resposta_fraude' => 'descricaoRespostaFraude',
        'origem_transacao' => 'origemTransacao',
        'codigo_modo_entrada_terminal' => 'codigoModoEntradaTerminal',
        'descricao_modo_entrada_terminal' => 'descricaoModoEntradaTerminal',
        'cpf' => 'cpf',
        'cnpj' => 'cnpj',
        'email' => 'email',
        'telefones' => 'telefones'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'id' => 'setId',
        'id_tipo_resolucao' => 'setIdTipoResolucao',
        'descricao_tipo_resolucao' => 'setDescricaoTipoResolucao',
        'flag_alto_risco' => 'setFlagAltoRisco',
        'id_conta' => 'setIdConta',
        'id_cartao' => 'setIdCartao',
        'id_produto' => 'setIdProduto',
        'id_transacao' => 'setIdTransacao',
        'data_transacao' => 'setDataTransacao',
        'valor_transacao' => 'setValorTransacao',
        'codigo_moeda_origem' => 'setCodigoMoedaOrigem',
        'valor_origem' => 'setValorOrigem',
        'codigo_moeda_destino' => 'setCodigoMoedaDestino',
        'valor_destino' => 'setValorDestino',
        'nome_estabelecimento' => 'setNomeEstabelecimento',
        'id_pais' => 'setIdPais',
        'codigo_resposta_autorizador' => 'setCodigoRespostaAutorizador',
        'descricao_resposta_autorizador' => 'setDescricaoRespostaAutorizador',
        'codigo_resposta_fraude' => 'setCodigoRespostaFraude',
        'descricao_resposta_fraude' => 'setDescricaoRespostaFraude',
        'origem_transacao' => 'setOrigemTransacao',
        'codigo_modo_entrada_terminal' => 'setCodigoModoEntradaTerminal',
        'descricao_modo_entrada_terminal' => 'setDescricaoModoEntradaTerminal',
        'cpf' => 'setCpf',
        'cnpj' => 'setCnpj',
        'email' => 'setEmail',
        'telefones' => 'setTelefones'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'id' => 'getId',
        'id_tipo_resolucao' => 'getIdTipoResolucao',
        'descricao_tipo_resolucao' => 'getDescricaoTipoResolucao',
        'flag_alto_risco' => 'getFlagAltoRisco',
        'id_conta' => 'getIdConta',
        'id_cartao' => 'getIdCartao',
        'id_produto' => 'getIdProduto',
        'id_transacao' => 'getIdTransacao',
        'data_transacao' => 'getDataTransacao',
        'valor_transacao' => 'getValorTransacao',
        'codigo_moeda_origem' => 'getCodigoMoedaOrigem',
        'valor_origem' => 'getValorOrigem',
        'codigo_moeda_destino' => 'getCodigoMoedaDestino',
        'valor_destino' => 'getValorDestino',
        'nome_estabelecimento' => 'getNomeEstabelecimento',
        'id_pais' => 'getIdPais',
        'codigo_resposta_autorizador' => 'getCodigoRespostaAutorizador',
        'descricao_resposta_autorizador' => 'getDescricaoRespostaAutorizador',
        'codigo_resposta_fraude' => 'getCodigoRespostaFraude',
        'descricao_resposta_fraude' => 'getDescricaoRespostaFraude',
        'origem_transacao' => 'getOrigemTransacao',
        'codigo_modo_entrada_terminal' => 'getCodigoModoEntradaTerminal',
        'descricao_modo_entrada_terminal' => 'getDescricaoModoEntradaTerminal',
        'cpf' => 'getCpf',
        'cnpj' => 'getCnpj',
        'email' => 'getEmail',
        'telefones' => 'getTelefones'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $id {{{risco_fraude_detalhado_response_id_value}}}
      * @var int
      */
    protected $id;
    
    /**
      * $id_tipo_resolucao {{{risco_fraude_detalhado_response_id_tipo_resolucao_value}}}
      * @var int
      */
    protected $id_tipo_resolucao;
    
    /**
      * $descricao_tipo_resolucao {{{risco_fraude_detalhado_response_descricao_tipo_resolucao_value}}}
      * @var string
      */
    protected $descricao_tipo_resolucao;
    
    /**
      * $flag_alto_risco {{{risco_fraude_detalhado_response_flag_alto_risco_value}}}
      * @var bool
      */
    protected $flag_alto_risco;
    
    /**
      * $id_conta {{{risco_fraude_detalhado_response_id_conta_value}}}
      * @var int
      */
    protected $id_conta;
    
    /**
      * $id_cartao {{{risco_fraude_detalhado_response_id_cartao_value}}}
      * @var int
      */
    protected $id_cartao;
    
    /**
      * $id_produto {{{risco_fraude_detalhado_response_id_produto_value}}}
      * @var int
      */
    protected $id_produto;
    
    /**
      * $id_transacao {{{risco_fraude_detalhado_response_id_transacao_value}}}
      * @var int
      */
    protected $id_transacao;
    
    /**
      * $data_transacao {{{risco_fraude_detalhado_response_data_transacao_value}}}
      * @var string
      */
    protected $data_transacao;
    
    /**
      * $valor_transacao {{{risco_fraude_detalhado_response_valor_transacao_value}}}
      * @var Number
      */
    protected $valor_transacao;
    
    /**
      * $codigo_moeda_origem {{{risco_fraude_detalhado_response_codigo_moeda_origem_value}}}
      * @var string
      */
    protected $codigo_moeda_origem;
    
    /**
      * $valor_origem {{{risco_fraude_detalhado_response_valor_origem_value}}}
      * @var Number
      */
    protected $valor_origem;
    
    /**
      * $codigo_moeda_destino {{{risco_fraude_detalhado_response_codigo_moeda_destino_value}}}
      * @var string
      */
    protected $codigo_moeda_destino;
    
    /**
      * $valor_destino {{{risco_fraude_detalhado_response_valor_destino_value}}}
      * @var Number
      */
    protected $valor_destino;
    
    /**
      * $nome_estabelecimento {{{risco_fraude_detalhado_response_nome_estabelecimento_value}}}
      * @var string
      */
    protected $nome_estabelecimento;
    
    /**
      * $id_pais {{{risco_fraude_detalhado_response_id_pais_value}}}
      * @var string
      */
    protected $id_pais;
    
    /**
      * $codigo_resposta_autorizador {{{risco_fraude_detalhado_response_codigo_resposta_autorizador_value}}}
      * @var string
      */
    protected $codigo_resposta_autorizador;
    
    /**
      * $descricao_resposta_autorizador {{{risco_fraude_detalhado_response_descricao_resposta_autorizador_value}}}
      * @var string
      */
    protected $descricao_resposta_autorizador;
    
    /**
      * $codigo_resposta_fraude {{{risco_fraude_detalhado_response_codigo_resposta_fraude_value}}}
      * @var string
      */
    protected $codigo_resposta_fraude;
    
    /**
      * $descricao_resposta_fraude {{{risco_fraude_detalhado_response_descricao_resposta_fraude_value}}}
      * @var string
      */
    protected $descricao_resposta_fraude;
    
    /**
      * $origem_transacao {{{risco_fraude_detalhado_response_origem_transacao_value}}}
      * @var string
      */
    protected $origem_transacao;
    
    /**
      * $codigo_modo_entrada_terminal {{{risco_fraude_detalhado_response_codigo_modo_entrada_terminal_value}}}
      * @var string
      */
    protected $codigo_modo_entrada_terminal;
    
    /**
      * $descricao_modo_entrada_terminal {{{risco_fraude_detalhado_response_descricao_modo_entrada_terminal_value}}}
      * @var string
      */
    protected $descricao_modo_entrada_terminal;
    
    /**
      * $cpf {{{risco_fraude_detalhado_response_cpf_value}}}
      * @var string
      */
    protected $cpf;
    
    /**
      * $cnpj {{{risco_fraude_detalhado_response_cnpj_value}}}
      * @var string
      */
    protected $cnpj;
    
    /**
      * $email {{{risco_fraude_detalhado_response_email_value}}}
      * @var string
      */
    protected $email;
    
    /**
      * $telefones {{{risco_fraude_detalhado_response_telefones_value}}}
      * @var \br.com.conductor.pier.api.v2.model\TelefoneResponse[]
      */
    protected $telefones;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->id = $data["id"];
            $this->id_tipo_resolucao = $data["id_tipo_resolucao"];
            $this->descricao_tipo_resolucao = $data["descricao_tipo_resolucao"];
            $this->flag_alto_risco = $data["flag_alto_risco"];
            $this->id_conta = $data["id_conta"];
            $this->id_cartao = $data["id_cartao"];
            $this->id_produto = $data["id_produto"];
            $this->id_transacao = $data["id_transacao"];
            $this->data_transacao = $data["data_transacao"];
            $this->valor_transacao = $data["valor_transacao"];
            $this->codigo_moeda_origem = $data["codigo_moeda_origem"];
            $this->valor_origem = $data["valor_origem"];
            $this->codigo_moeda_destino = $data["codigo_moeda_destino"];
            $this->valor_destino = $data["valor_destino"];
            $this->nome_estabelecimento = $data["nome_estabelecimento"];
            $this->id_pais = $data["id_pais"];
            $this->codigo_resposta_autorizador = $data["codigo_resposta_autorizador"];
            $this->descricao_resposta_autorizador = $data["descricao_resposta_autorizador"];
            $this->codigo_resposta_fraude = $data["codigo_resposta_fraude"];
            $this->descricao_resposta_fraude = $data["descricao_resposta_fraude"];
            $this->origem_transacao = $data["origem_transacao"];
            $this->codigo_modo_entrada_terminal = $data["codigo_modo_entrada_terminal"];
            $this->descricao_modo_entrada_terminal = $data["descricao_modo_entrada_terminal"];
            $this->cpf = $data["cpf"];
            $this->cnpj = $data["cnpj"];
            $this->email = $data["email"];
            $this->telefones = $data["telefones"];
        }
    }
    
    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
  
    /**
     * Sets id
     * @param int $id {{{risco_fraude_detalhado_response_id_value}}}
     * @return $this
     */
    public function setId($id)
    {
        
        $this->id = $id;
        return $this;
    }
    
    /**
     * Gets id_tipo_resolucao
     * @return int
     */
    public function getIdTipoResolucao()
    {
        return $this->id_tipo_resolucao;
    }
  
    /**
     * Sets id_tipo_resolucao
     * @param int $id_tipo_resolucao {{{risco_fraude_detalhado_response_id_tipo_resolucao_value}}}
     * @return $this
     */
    public function setIdTipoResolucao($id_tipo_resolucao)
    {
        
        $this->id_tipo_resolucao = $id_tipo_resolucao;
        return $this;
    }
    
    /**
     * Gets descricao_tipo_resolucao
     * @return string
     */
    public function getDescricaoTipoResolucao()
    {
        return $this->descricao_tipo_resolucao;
    }
  
    /**
     * Sets descricao_tipo_resolucao
     * @param string $descricao_tipo_resolucao {{{risco_fraude_detalhado_response_descricao_tipo_resolucao_value}}}
     * @return $this
     */
    public function setDescricaoTipoResolucao($descricao_tipo_resolucao)
    {
        
        $this->descricao_tipo_resolucao = $descricao_tipo_resolucao;
        return $this;
    }
    
    /**
     * Gets flag_alto_risco
     * @return bool
     */
    public function getFlagAltoRisco()
    {
        return $this->flag_alto_risco;
    }
  
    /**
     * Sets flag_alto_risco
     * @param bool $flag_alto_risco {{{risco_fraude_detalhado_response_flag_alto_risco_value}}}
     * @return $this
     */
    public function setFlagAltoRisco($flag_alto_risco)
    {
        
        $this->flag_alto_risco = $flag_alto_risco;
        return $this;
    }
    
    /**
     * Gets id_conta
     * @return int
     */
    public function getIdConta()
    {
        return $this->id_conta;
    }
  
    /**
     * Sets id_conta
     * @param int $id_conta {{{risco_fraude_detalhado_response_id_conta_value}}}
     * @return $this
     */
    public function setIdConta($id_conta)
    {
        
        $this->id_conta = $id_conta;
        return $this;
    }
    
    /**
     * Gets id_cartao
     * @return int
     */
    public function getIdCartao()
    {
        return $this->id_cartao;
    }
  
    /**
     * Sets id_cartao
     * @param int $id_cartao {{{risco_fraude_detalhado_response_id_cartao_value}}}
     * @return $this
     */
    public function setIdCartao($id_cartao)
    {
        
        $this->id_cartao = $id_cartao;
        return $this;
    }
    
    /**
     * Gets id_produto
     * @return int
     */
    public function getIdProduto()
    {
        return $this->id_produto;
    }
  
    /**
     * Sets id_produto
     * @param int $id_produto {{{risco_fraude_detalhado_response_id_produto_value}}}
     * @return $this
     */
    public function setIdProduto($id_produto)
    {
        
        $this->id_produto = $id_produto;
        return $this;
    }
    
    /**
     * Gets id_transacao
     * @return int
     */
    public function getIdTransacao()
    {
        return $this->id_transacao;
    }
  
    /**
     * Sets id_transacao
     * @param int $id_transacao {{{risco_fraude_detalhado_response_id_transacao_value}}}
     * @return $this
     */
    public function setIdTransacao($id_transacao)
    {
        
        $this->id_transacao = $id_transacao;
        return $this;
    }
    
    /**
     * Gets data_transacao
     * @return string
     */
    public function getDataTransacao()
    {
        return $this->data_transacao;
    }
  
    /**
     * Sets data_transacao
     * @param string $data_transacao {{{risco_fraude_detalhado_response_data_transacao_value}}}
     * @return $this
     */
    public function setDataTransacao($data_transacao)
    {
        
        $this->data_transacao = $data_transacao;
        return $this;
    }
    
    /**
     * Gets valor_transacao
     * @return Number
     */
    public function getValorTransacao()
    {
        return $this->valor_transacao;
    }
  
    /**
     * Sets valor_transacao
     * @param Number $valor_transacao {{{risco_fraude_detalhado_response_valor_transacao_value}}}
     * @return $this
     */
    public function setValorTransacao($valor_transacao)
    {
        
        $this->valor_transacao = $valor_transacao;
        return $this;
    }
    
    /**
     * Gets codigo_moeda_origem
     * @return string
     */
    public function getCodigoMoedaOrigem()
    {
        return $this->codigo_moeda_origem;
    }
  
    /**
     * Sets codigo_moeda_origem
     * @param string $codigo_moeda_origem {{{risco_fraude_detalhado_response_codigo_moeda_origem_value}}}
     * @return $this
     */
    public function setCodigoMoedaOrigem($codigo_moeda_origem)
    {
        
        $this->codigo_moeda_origem = $codigo_moeda_origem;
        return $this;
    }
    
    /**
     * Gets valor_origem
     * @return Number
     */
    public function getValorOrigem()
    {
        return $this->valor_origem;
    }
  
    /**
     * Sets valor_origem
     * @param Number $valor_origem {{{risco_fraude_detalhado_response_valor_origem_value}}}
     * @return $this
     */
    public function setValorOrigem($valor_origem)
    {
        
        $this->valor_origem = $valor_origem;
        return $this;
    }
    
    /**
     * Gets codigo_moeda_destino
     * @return string
     */
    public function getCodigoMoedaDestino()
    {
        return $this->codigo_moeda_destino;
    }
  
    /**
     * Sets codigo_moeda_destino
     * @param string $codigo_moeda_destino {{{risco_fraude_detalhado_response_codigo_moeda_destino_value}}}
     * @return $this
     */
    public function setCodigoMoedaDestino($codigo_moeda_destino)
    {
        
        $this->codigo_moeda_destino = $codigo_moeda_destino;
        return $this;
    }
    
    /**
     * Gets valor_destino
     * @return Number
     */
    public function getValorDestino()
    {
        return $this->valor_destino;
    }
  
    /**
     * Sets valor_destino
     * @param Number $valor_destino {{{risco_fraude_detalhado_response_valor_destino_value}}}
     * @return $this
     */
    public function setValorDestino($valor_destino)
    {
        
        $this->valor_destino = $valor_destino;
        return $this;
    }
    
    /**
     * Gets nome_estabelecimento
     * @return string
     */
    public function getNomeEstabelecimento()
    {
        return $this->nome_estabelecimento;
    }
  
    /**
     * Sets nome_estabelecimento
     * @param string $nome_estabelecimento {{{risco_fraude_detalhado_response_nome_estabelecimento_value}}}
     * @return $this
     */
    public function setNomeEstabelecimento($nome_estabelecimento)
    {
        
        $this->nome_estabelecimento = $nome_estabelecimento;
        return $this;
    }
    
    /**
     * Gets id_pais
     * @return string
     */
    public function getIdPais()
    {
        return $this->id_pais;
    }
  
    /**
     * Sets id_pais
     * @param string $id_pais {{{risco_fraude_detalhado_response_id_pais_value}}}
     * @return $this
     */
    public function setIdPais($id_pais)
    {
        
        $this->id_pais = $id_pais;
        return $this;
    }
    
    /**
     * Gets codigo_resposta_autorizador
     * @return string
     */
    public function getCodigoRespostaAutorizador()
    {
        return $this->codigo_resposta_autorizador;
    }
  
    /**
     * Sets codigo_resposta_autorizador
     * @param string $codigo_resposta_autorizador {{{risco_fraude_detalhado_response_codigo_resposta_autorizador_value}}}
     * @return $this
     */
    public function setCodigoRespostaAutorizador($codigo_resposta_autorizador)
    {
        
        $this->codigo_resposta_autorizador = $codigo_resposta_autorizador;
        return $this;
    }
    
    /**
     * Gets descricao_resposta_autorizador
     * @return string
     */
    public function getDescricaoRespostaAutorizador()
    {
        return $this->descricao_resposta_autorizador;
    }
  
    /**
     * Sets descricao_resposta_autorizador
     * @param string $descricao_resposta_autorizador {{{risco_fraude_detalhado_response_descricao_resposta_autorizador_value}}}
     * @return $this
     */
    public function setDescricaoRespostaAutorizador($descricao_resposta_autorizador)
    {
        
        $this->descricao_resposta_autorizador = $descricao_resposta_autorizador;
        return $this;
    }
    
    /**
     * Gets codigo_resposta_fraude
     * @return string
     */
    public function getCodigoRespostaFraude()
    {
        return $this->codigo_resposta_fraude;
    }
  
    /**
     * Sets codigo_resposta_fraude
     * @param string $codigo_resposta_fraude {{{risco_fraude_detalhado_response_codigo_resposta_fraude_value}}}
     * @return $this
     */
    public function setCodigoRespostaFraude($codigo_resposta_fraude)
    {
        
        $this->codigo_resposta_fraude = $codigo_resposta_fraude;
        return $this;
    }
    
    /**
     * Gets descricao_resposta_fraude
     * @return string
     */
    public function getDescricaoRespostaFraude()
    {
        return $this->descricao_resposta_fraude;
    }
  
    /**
     * Sets descricao_resposta_fraude
     * @param string $descricao_resposta_fraude {{{risco_fraude_detalhado_response_descricao_resposta_fraude_value}}}
     * @return $this
     */
    public function setDescricaoRespostaFraude($descricao_resposta_fraude)
    {
        
        $this->descricao_resposta_fraude = $descricao_resposta_fraude;
        return $this;
    }
    
    /**
     * Gets origem_transacao
     * @return string
     */
    public function getOrigemTransacao()
    {
        return $this->origem_transacao;
    }
  
    /**
     * Sets origem_transacao
     * @param string $origem_transacao {{{risco_fraude_detalhado_response_origem_transacao_value}}}
     * @return $this
     */
    public function setOrigemTransacao($origem_transacao)
    {
        
        $this->origem_transacao = $origem_transacao;
        return $this;
    }
    
    /**
     * Gets codigo_modo_entrada_terminal
     * @return string
     */
    public function getCodigoModoEntradaTerminal()
    {
        return $this->codigo_modo_entrada_terminal;
    }
  
    /**
     * Sets codigo_modo_entrada_terminal
     * @param string $codigo_modo_entrada_terminal {{{risco_fraude_detalhado_response_codigo_modo_entrada_terminal_value}}}
     * @return $this
     */
    public function setCodigoModoEntradaTerminal($codigo_modo_entrada_terminal)
    {
        
        $this->codigo_modo_entrada_terminal = $codigo_modo_entrada_terminal;
        return $this;
    }
    
    /**
     * Gets descricao_modo_entrada_terminal
     * @return string
     */
    public function getDescricaoModoEntradaTerminal()
    {
        return $this->descricao_modo_entrada_terminal;
    }
  
    /**
     * Sets descricao_modo_entrada_terminal
     * @param string $descricao_modo_entrada_terminal {{{risco_fraude_detalhado_response_descricao_modo_entrada_terminal_value}}}
     * @return $this
     */
    public function setDescricaoModoEntradaTerminal($descricao_modo_entrada_terminal)
    {
        
        $this->descricao_modo_entrada_terminal = $descricao_modo_entrada_terminal;
        return $this;
    }
    
    /**
     * Gets cpf
     * @return string
     */
    public function getCpf()
    {
        return $this->cpf;
    }
  
    /**
     * Sets cpf
     * @param string $cpf {{{risco_fraude_detalhado_response_cpf_value}}}
     * @return $this
     */
    public function setCpf($cpf)
    {
        
        $this->cpf = $cpf;
        return $this;
    }
    
    /**
     * Gets cnpj
     * @return string
     */
    public function getCnpj()
    {
        return $this->cnpj;
    }
  
    /**
     * Sets cnpj
     * @param string $cnpj {{{risco_fraude_detalhado_response_cnpj_value}}}
     * @return $this
     */
    public function setCnpj($cnpj)
    {
        
        $this->cnpj = $cnpj;
        return $this;
    }
    
    /**
     * Gets email
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }
  
    /**
     * Sets email
     * @param string $email {{{risco_fraude_detalhado_response_email_value}}}
     * @return $this
     */
    public function setEmail($email)
    {
        
        $this->email = $email;
        return $this;
    }
    
    /**
     * Gets telefones
     * @return \br.com.conductor.pier.api.v2.model\TelefoneResponse[]
     */
    public function getTelefones()
    {
        return $this->telefones;
    }
  
    /**
     * Sets telefones
     * @param \br.com.conductor.pier.api.v2.model\TelefoneResponse[] $telefones {{{risco_fraude_detalhado_response_telefones_value}}}
     * @return $this
     */
    public function setTelefones($telefones)
    {
        
        $this->telefones = $telefones;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\br.com.conductor.pier.api.v2.invoker\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\br.com.conductor.pier.api.v2.invoker\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
